; MurkyCorps ESP32 companion device
; Target: LILYGO T-Display-S3 CAP TOUCH
; Upload: pio run -t upload
; Monitor: pio device monitor

[env:tdisplay-s3]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_build.flash_size          = 16MB
board_build.psram_type          = opi
board_upload.flash_size         = 16MB

lib_deps =
  lovyan03/LovyanGFX@^1.1.16
  bblanchon/ArduinoJson@^7.1.0
  h2zero/NimBLE-Arduino@^1.4.2

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=0

monitor_speed   = 115200
monitor_filters = esp32_exception_decoder
